dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-05/run.sh |
  bash
notifications:
  slack:
    secure: d4ppGb3a9tYqSKDgaYTkt8rlswpZhoPpjNYZjBADYQRMd7eHP/rGjv54/B0vL9abEXlg6afz9tRQBIly3iGLp/FZFyAqfn19yp7b9KmCvbOh7LARHmW05bOdZutvoOs1mgjPiaesCTMkltLc3zBm6X4avZevl5/trVHz3pvTvOHRpeWh8Hm+16FMzCc+6c1Fi9Ouj5cIkxQ0Neg2Xot8QUJj1X8vqNTSggwe8mDlDm0Tk7l48hRXLlltO9hf+vKsKhuHEF2qH47M7dfNL3cIISXpYPGQQHtEVViFjWgXNkG4JTriXtbrWjkuSy6fDm787ejLJZ0Ui4EIx2m+2miuNPYR65pKnq6JT/rXoYv7WeAr0E7bAIMZLBRJ6UkcuiC5up47MReqHUlIERWwObmRvvNiyxEoykcWnHuvx7sSqsI42fyHVsIcrTW5p9Jaaph6MW05d1l/bq31/I3hn/jTXSttTqja0clOaMMLZAwmpY0OnITNSFKeWzTSYcrDEvEpNUwCKCA9bvaq6vXrEkiS07suuayU3IPCzlY+SiXkmjhNCnV0yWtY1lohhkNCTl3obl/qHSI1HJjoBQuDKUb1QPQxT4egHN1JLeSbtEVpKZfPfxWVt+8Ok+BvEfaNzT7N/r65HCkUzvpS2Q9a4e9xC0CPfYdnAEuso+UiRscdrPk=
