dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-05/run.sh |
  bash
notifications:
  slack:
    secure: jngm0Y1irdOOajv6UmJrXWQKntdcnMe4wiFTk55f1JCJp24JrCtdXi8mia56De3Tmi0oi5zqh1CerYr8mLGq0RwnMP9wUna35aVCQY+gvwkgohzsB41ozJ+0t7AOL/8LgFNnRJum8Ka5S502NlfMy8HtcopWV0TiBX61CiUrzcYMS0dqKVQMrQ6rFvpseAfnpuYbSar0F5mp3siKbO5vNLqiERUUMYE0S1akq00I8c+pGdLBH8Xr/qP8zP4Odj5kf96jblLV9IrRf/uAPaJ6aaHnUl9ZrvsA7jHhkpiUYFnTG6dGBEumHBUpGE/xsgLrDQNiE9g1yHG08y8MXL9z43Qf9wsJGtKjzG0i32UtbbODaiM60vllhjGLo692QNp1EOkOsykM+PDARTRzZpNLR3ziQotCNYGQaWwqrtxoLIG20x43BSy3mjIbmmr2v+kTf++74jW2ttyr5jVBilwubH/v3561mcerLo+oYEBFzgA4PAuuoSfh7vYWAtkgLvZJN+bNepx/EUapB+W88t4unZVXsnNeog4TZoKAOAJyB4vkswJ8YmcSJ2Q+mtc9aAefHMfFktZ3wghU4kweCjXyvBVDq0S72eyWbepMcj67nrW0Z1F8uQPiSQ1dk7HgxHMeMv7tHNmtkdoAZGiPkGVaKMqoD0ALQu1yQ182FRqaWyA=
