---
- name: install mongodb v.3.2
  hosts: all
  become: true
  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927

  # Remove specified repository from sources list.
  - name: Add repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb
    apt:
      name:  mongodb-org-3.2
      state: present

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
